import pdfMake from 'pdfmake/build/pdfmake';
import vfs from 'pdfmake/build/vfs_fonts';
import type { Content, TDocumentDefinitions } from 'pdfmake/interfaces';
import type { CompanyProfile } from './companyProfileService';
import { formatCurrency, formatDate } from './formatters';

pdfMake.addVirtualFileSystem(vfs);

/**
 * Closes the "Output" gap (BLUEPRINT.md §8.1/§8.7) — printable/PDF document generation for the
 * three real transaction documents (Sales Invoice, Credit Memo, APV). Client-side only (pdfmake
 * ships its own font data via vfs_fonts, no server — this app is a static SPA, adapter-static,
 * §2.6), stamping the seller identity captured in Company Profile (companyProfileService.ts)
 * onto the actual document face BIR requires it on. Every doc-type builds a `TDocumentDefinitions`
 * and hands it to `emit()`, which either downloads a real .pdf file or opens the browser's print
 * dialog directly against the same generated document — same underlying content either way.
 */
export type PdfAction = 'download' | 'print';

function money(n: number | undefined): string {
  return formatCurrency(n || 0);
}

function emit(docDefinition: TDocumentDefinitions, filename: string, action: PdfAction): void {
  const created = pdfMake.createPdf(docDefinition);
  if (action === 'print') {
    created.print();
  } else {
    created.download(filename);
  }
}

/** Seller identity block (Company Profile) + document title/number/dates — shared by every doc type. */
function buildHeader(company: CompanyProfile, docTitle: string, docNo: string, dateLines: Content[]): Content {
  const sellerName = company.tradeName?.trim() ? `${company.registeredName} (${company.tradeName})` : company.registeredName;
  const vatStatusLabel = company.vatStatus === 'vat' ? 'VAT Registered' : 'Non-VAT';
  return {
    columns: [
      [
        { text: sellerName || 'Registered Business Name Not Set', style: 'sellerName' },
        { text: company.registeredAddress || '', style: 'small' },
        { text: `TIN: ${company.tin || 'N/A'}${company.rdoCode ? '  RDO: ' + company.rdoCode : ''}`, style: 'small' },
        { text: vatStatusLabel, style: 'small', bold: true }
      ],
      [
        { text: docTitle, style: 'docTitle', alignment: 'right' },
        { text: `No. ${docNo}`, style: 'docNo', alignment: 'right' },
        ...dateLines
      ]
    ]
  };
}

const styles = {
  sellerName: { fontSize: 13, bold: true },
  docTitle: { fontSize: 16, bold: true },
  docNo: { fontSize: 11, bold: true },
  small: { fontSize: 8, color: '#555555' },
  label: { fontSize: 8, color: '#888888', margin: [0, 0, 0, 2] as [number, number, number, number] },
  tableHeader: { fontSize: 9, bold: true, fillColor: '#f2f2f2' },
  cell: { fontSize: 9 },
  footer: { fontSize: 7, color: '#888888', italics: true }
};

const FOOTER_NOTE =
  'This document is not valid for claim of input tax unless the seller is VAT-registered and this document bears the required BIR registration details. Generated by DigiSoft CAS.';

// -------------------------------------------------------------------------------------------
// Sales Invoice
// -------------------------------------------------------------------------------------------

export interface InvoicePdfLineItem {
  itemName: string;
  description: string;
  unitName: string;
  qty: number;
  price: number;
  amount: number;
}

export interface InvoicePdfData {
  invoiceNo: string;
  invoiceDate: Date | { seconds: number } | string;
  dueDate?: Date | { seconds: number } | string;
  customerName: string;
  customerAddress?: string;
  customerTin?: string;
  poNumber?: string;
  termsName?: string;
  paymentMethodName?: string;
  lineItems: InvoicePdfLineItem[];
  grossAmount: number;
  discount: number;
  netSales: number;
  vatableSales: number;
  zeroRated: number;
  vatExempt: number;
  vat: number;
  lessWithholding: number;
  totalDue: number;
}

function buildSalesInvoiceDocDefinition(invoice: InvoicePdfData, company: CompanyProfile): TDocumentDefinitions {
  return {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
    content: [
      buildHeader(company, 'SALES INVOICE', invoice.invoiceNo, [
        { text: `Date: ${formatDate(invoice.invoiceDate as any)}`, style: 'small', alignment: 'right' },
        ...(invoice.dueDate ? [{ text: `Due: ${formatDate(invoice.dueDate as any)}`, style: 'small', alignment: 'right' as const }] : [])
      ]),
      { canvas: [{ type: 'line', x1: 0, y1: 10, x2: 515, y2: 10, lineWidth: 1 }] },
      {
        margin: [0, 12, 0, 12],
        columns: [
          [
            { text: 'Bill To', style: 'label' },
            { text: invoice.customerName, bold: true },
            ...(invoice.customerAddress ? [{ text: invoice.customerAddress, style: 'small' }] : []),
            ...(invoice.customerTin ? [{ text: `TIN: ${invoice.customerTin}`, style: 'small' }] : [])
          ],
          [
            ...(invoice.poNumber ? [{ text: `PO #: ${invoice.poNumber}`, style: 'small', alignment: 'right' as const }] : []),
            ...(invoice.termsName ? [{ text: `Terms: ${invoice.termsName}`, style: 'small', alignment: 'right' as const }] : []),
            ...(invoice.paymentMethodName ? [{ text: `Payment Method: ${invoice.paymentMethodName}`, style: 'small', alignment: 'right' as const }] : [])
          ]
        ]
      },
      {
        table: {
          headerRows: 1,
          widths: ['*', 40, 50, 60, 60],
          body: [
            [
              { text: 'Description', style: 'tableHeader' },
              { text: 'Qty', style: 'tableHeader', alignment: 'right' },
              { text: 'Unit', style: 'tableHeader' },
              { text: 'Price', style: 'tableHeader', alignment: 'right' },
              { text: 'Amount', style: 'tableHeader', alignment: 'right' }
            ],
            ...invoice.lineItems.map((li) => [
              { text: li.itemName ? `${li.itemName}${li.description ? ' - ' + li.description : ''}` : li.description, style: 'cell' },
              { text: String(li.qty), style: 'cell', alignment: 'right' as const },
              { text: li.unitName || '', style: 'cell' },
              { text: money(li.price), style: 'cell', alignment: 'right' as const },
              { text: money(li.amount), style: 'cell', alignment: 'right' as const }
            ])
          ]
        },
        layout: 'lightHorizontalLines'
      },
      {
        margin: [0, 12, 0, 0],
        columns: [
          { text: '', width: '*' },
          {
            width: 220,
            table: {
              widths: ['*', 80],
              body: [
                ['Gross Amount', { text: money(invoice.grossAmount), alignment: 'right' }],
                ...(invoice.discount ? [['Discount', { text: money(invoice.discount), alignment: 'right' as const }]] : []),
                ['Net Sales', { text: money(invoice.netSales), alignment: 'right' }],
                ...(invoice.vatableSales ? [['VATable Sales', { text: money(invoice.vatableSales), alignment: 'right' as const }]] : []),
                ...(invoice.zeroRated ? [['Zero-Rated Sales', { text: money(invoice.zeroRated), alignment: 'right' as const }]] : []),
                ...(invoice.vatExempt ? [['VAT-Exempt Sales', { text: money(invoice.vatExempt), alignment: 'right' as const }]] : []),
                ['VAT (12%)', { text: money(invoice.vat), alignment: 'right' }],
                ...(invoice.lessWithholding ? [['Less: Withholding Tax', { text: '(' + money(invoice.lessWithholding) + ')', alignment: 'right' as const }]] : []),
                [{ text: 'Total Due', bold: true }, { text: money(invoice.totalDue), alignment: 'right', bold: true }]
              ]
            },
            layout: 'lightHorizontalLines'
          }
        ]
      },
      { margin: [0, 24, 0, 0], text: FOOTER_NOTE, style: 'footer' }
    ],
    styles,
    defaultStyle: { fontSize: 9 }
  };
}

export function generateSalesInvoicePdf(invoice: InvoicePdfData, company: CompanyProfile, action: PdfAction = 'download'): void {
  emit(buildSalesInvoiceDocDefinition(invoice, company), `${invoice.invoiceNo || 'invoice'}.pdf`, action);
}

// -------------------------------------------------------------------------------------------
// Credit Memo
// -------------------------------------------------------------------------------------------

export interface CreditMemoPdfLineItem {
  itemName: string;
  description: string;
  unitName: string;
  qty: number;
  unitPrice: number;
  amount: number;
}

export interface CreditMemoPdfData {
  cmNo: string;
  cmDate: Date | { seconds: number } | string;
  customerName: string;
  customerAddress?: string;
  customerTin?: string;
  reference?: string;
  lineItems: CreditMemoPdfLineItem[];
  netSales: number;
  vatableSales: number;
  zeroRated: number;
  vatExempt: number;
  vat: number;
  lessWithholding: number;
  totalDue: number;
}

function buildCreditMemoDocDefinition(cm: CreditMemoPdfData, company: CompanyProfile): TDocumentDefinitions {
  return {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
    content: [
      buildHeader(company, 'CREDIT MEMO', cm.cmNo, [{ text: `Date: ${formatDate(cm.cmDate as any)}`, style: 'small', alignment: 'right' }]),
      { canvas: [{ type: 'line', x1: 0, y1: 10, x2: 515, y2: 10, lineWidth: 1 }] },
      {
        margin: [0, 12, 0, 12],
        columns: [
          [
            { text: 'Issued To', style: 'label' },
            { text: cm.customerName, bold: true },
            ...(cm.customerAddress ? [{ text: cm.customerAddress, style: 'small' }] : []),
            ...(cm.customerTin ? [{ text: `TIN: ${cm.customerTin}`, style: 'small' }] : [])
          ],
          [...(cm.reference ? [{ text: `Reference: ${cm.reference}`, style: 'small', alignment: 'right' as const }] : [])]
        ]
      },
      {
        table: {
          headerRows: 1,
          widths: ['*', 40, 50, 60, 60],
          body: [
            [
              { text: 'Description', style: 'tableHeader' },
              { text: 'Qty', style: 'tableHeader', alignment: 'right' },
              { text: 'Unit', style: 'tableHeader' },
              { text: 'Price', style: 'tableHeader', alignment: 'right' },
              { text: 'Amount', style: 'tableHeader', alignment: 'right' }
            ],
            ...cm.lineItems.map((li) => [
              { text: li.itemName ? `${li.itemName}${li.description ? ' - ' + li.description : ''}` : li.description, style: 'cell' },
              { text: String(li.qty), style: 'cell', alignment: 'right' as const },
              { text: li.unitName || '', style: 'cell' },
              { text: money(li.unitPrice), style: 'cell', alignment: 'right' as const },
              { text: money(li.amount), style: 'cell', alignment: 'right' as const }
            ])
          ]
        },
        layout: 'lightHorizontalLines'
      },
      {
        margin: [0, 12, 0, 0],
        columns: [
          { text: '', width: '*' },
          {
            width: 220,
            table: {
              widths: ['*', 80],
              body: [
                ['Net Sales', { text: money(cm.netSales), alignment: 'right' }],
                ...(cm.vatableSales ? [['VATable Sales', { text: money(cm.vatableSales), alignment: 'right' as const }]] : []),
                ...(cm.zeroRated ? [['Zero-Rated Sales', { text: money(cm.zeroRated), alignment: 'right' as const }]] : []),
                ...(cm.vatExempt ? [['VAT-Exempt Sales', { text: money(cm.vatExempt), alignment: 'right' as const }]] : []),
                ['VAT (12%)', { text: money(cm.vat), alignment: 'right' }],
                ...(cm.lessWithholding ? [['Less: Withholding Tax', { text: '(' + money(cm.lessWithholding) + ')', alignment: 'right' as const }]] : []),
                [{ text: 'Total Amount', bold: true }, { text: money(cm.totalDue), alignment: 'right', bold: true }]
              ]
            },
            layout: 'lightHorizontalLines'
          }
        ]
      },
      { margin: [0, 24, 0, 0], text: FOOTER_NOTE, style: 'footer' }
    ],
    styles,
    defaultStyle: { fontSize: 9 }
  };
}

export function generateCreditMemoPdf(cm: CreditMemoPdfData, company: CompanyProfile, action: PdfAction = 'download'): void {
  emit(buildCreditMemoDocDefinition(cm, company), `${cm.cmNo || 'credit-memo'}.pdf`, action);
}

// -------------------------------------------------------------------------------------------
// APV (Accounts Payable Voucher) — a purchase/disbursement document, not a sale: the "seller"
// header block is still this business's own Company Profile (it's the one issuing the
// voucher), but the counterparty block is the vendor being paid, labeled "Payee" not "Bill To".
// No vatable/zero-rated/exempt split field exists on APV (BLUEPRINT.md §3.4) — only a flat
// net/VAT/total, unlike Sales Invoice/Credit Memo.
// -------------------------------------------------------------------------------------------

export interface ApvPdfLineItem {
  accountName: string;
  costCenterName?: string;
  description: string;
  amount: number;
  dsc: number;
  total: number;
}

export interface ApvPdfData {
  apvNo: string;
  apvDate: Date | { seconds: number } | string;
  dueDate?: Date | { seconds: number } | string;
  vendorName: string;
  vendorAddress?: string;
  vendorTin?: string;
  referenceNo?: string;
  poNumber?: string;
  lineItems: ApvPdfLineItem[];
  grossAmount: number;
  discount: number;
  netAmount: number;
  vat: number;
  lessWithholding: number;
  totalAmountDue: number;
}

function buildApvDocDefinition(apv: ApvPdfData, company: CompanyProfile): TDocumentDefinitions {
  return {
    pageSize: 'A4',
    pageMargins: [40, 40, 40, 40],
    content: [
      buildHeader(company, 'ACCOUNTS PAYABLE VOUCHER', apv.apvNo, [
        { text: `Date: ${formatDate(apv.apvDate as any)}`, style: 'small', alignment: 'right' },
        ...(apv.dueDate ? [{ text: `Due: ${formatDate(apv.dueDate as any)}`, style: 'small', alignment: 'right' as const }] : [])
      ]),
      { canvas: [{ type: 'line', x1: 0, y1: 10, x2: 515, y2: 10, lineWidth: 1 }] },
      {
        margin: [0, 12, 0, 12],
        columns: [
          [
            { text: 'Payee', style: 'label' },
            { text: apv.vendorName, bold: true },
            ...(apv.vendorAddress ? [{ text: apv.vendorAddress, style: 'small' }] : []),
            ...(apv.vendorTin ? [{ text: `TIN: ${apv.vendorTin}`, style: 'small' }] : [])
          ],
          [
            ...(apv.referenceNo ? [{ text: `Reference #: ${apv.referenceNo}`, style: 'small', alignment: 'right' as const }] : []),
            ...(apv.poNumber ? [{ text: `PO #: ${apv.poNumber}`, style: 'small', alignment: 'right' as const }] : [])
          ]
        ]
      },
      {
        table: {
          headerRows: 1,
          widths: ['*', '*', 60, 40, 60],
          body: [
            [
              { text: 'Account', style: 'tableHeader' },
              { text: 'Description', style: 'tableHeader' },
              { text: 'Amount', style: 'tableHeader', alignment: 'right' },
              { text: 'DSC %', style: 'tableHeader', alignment: 'right' },
              { text: 'Total', style: 'tableHeader', alignment: 'right' }
            ],
            ...apv.lineItems.map((li) => [
              { text: li.accountName + (li.costCenterName ? ` (${li.costCenterName})` : ''), style: 'cell' },
              { text: li.description, style: 'cell' },
              { text: money(li.amount), style: 'cell', alignment: 'right' as const },
              { text: li.dsc ? `${li.dsc}%` : '-', style: 'cell', alignment: 'right' as const },
              { text: money(li.total), style: 'cell', alignment: 'right' as const }
            ])
          ]
        },
        layout: 'lightHorizontalLines'
      },
      {
        margin: [0, 12, 0, 0],
        columns: [
          { text: '', width: '*' },
          {
            width: 220,
            table: {
              widths: ['*', 80],
              body: [
                ['Gross Amount', { text: money(apv.grossAmount), alignment: 'right' }],
                ...(apv.discount ? [['Discount', { text: money(apv.discount), alignment: 'right' as const }]] : []),
                ['Net Amount', { text: money(apv.netAmount), alignment: 'right' }],
                ['Input VAT (12%)', { text: money(apv.vat), alignment: 'right' }],
                ...(apv.lessWithholding ? [['Less: Withholding Tax', { text: '(' + money(apv.lessWithholding) + ')', alignment: 'right' as const }]] : []),
                [{ text: 'Total Amount Due', bold: true }, { text: money(apv.totalAmountDue), alignment: 'right', bold: true }]
              ]
            },
            layout: 'lightHorizontalLines'
          }
        ]
      },
      { margin: [0, 24, 0, 0], text: 'Generated by DigiSoft CAS.', style: 'footer' }
    ],
    styles,
    defaultStyle: { fontSize: 9 }
  };
}

export function generateApvPdf(apv: ApvPdfData, company: CompanyProfile, action: PdfAction = 'download'): void {
  emit(buildApvDocDefinition(apv, company), `${apv.apvNo || 'apv'}.pdf`, action);
}
